export type TBackgrounds =
    | 'Buttercream'
    | 'Solitary Star'
    | 'Snow White'
    | 'Cannoli Cream'
    | 'Bit of blue'
    | 'Marshmallow'
    | 'Phantom Green'
    | 'Vanilla Ice';

export type TFur =
    | 'Chestnut'
    | 'Sand Dollar'
    | 'Bone'
    | 'Stone'
    | 'Pewter'
    | 'Pink Marshmallow'
    | 'Wheat'
    | 'Tumbleweed'
    | 'Eggnog'
    | 'Hazel'
    | 'Paradise Green';

export type TFace = 'Smile' | 'Chill' | 'Smirk' | 'Blasé' | 'Wholesome';

export type TClothes =
    | 'Bear Coat'
    | 'None'
    | 'Banana Hazmat'
    | 'Ace Cardigan'
    | 'Stolen Hotel Robe'
    | 'Orange Hoodie'
    | 'C.R.E.A.M. Hoodie'
    | 'McY00ts Polo'
    | 'Classic Suit'
    | 'Black Puff Jacket'
    | 'The Hoodie'
    | 'Cherry Puffer'
    | 'Baseball Hoodie'
    | 'Basketball Jersey'
    | 'Blue Sky Hoodie'
    | 'Blue Headphones'
    | 'Army T-shirt'
    | 'Professor'
    | 'Marshmallow Puffer'
    | 'Rare T-shirt'
    | 'Windbreaker (blackout)'
    | 'Cream Flannel'
    | 'Happy Hoodie'
    | 'Miracle Jersey'
    | 'Football Jersey'
    | 'Black Tracksuit'
    | 'Sunday Shirt'
    | 'Summer Shirt'
    | 'Thrifted Denim Jacket'
    | 'Nice Overalls'
    | 'Mechanic'
    | 'Fast Jacket'
    | 'Blob Suit'
    | 'Billionaire Zip-up'
    | 'Jacksonhole Jacket'
    | 'Varsity Jacket'
    | 'Cashmere Turtleneck'
    | 'Banana Puffer'
    | 'Angler Vest'
    | 'Rugby Shirt';

export type THead =
    | 'Pyrite Crown'
    | 'Color Block Halo'
    | '24k Gold Shoey Guzzler'
    | 'Frank Headband'
    | 'Money Bands'
    | 'Champ Hat'
    | 'McY00ts Visor'
    | 'Red Horns'
    | 'Backwards Snapback'
    | 'None'
    | 'Windswept Hair'
    | 'Spiky Hair'
    | 'Happy Hat'
    | 'Orange Beanie'
    | 'Mullet'
    | 'Free Snapback'
    | 'Headphones'
    | 'Down Bad Snapback'
    | 'Minimalist Camo Cap'
    | 'W Visor'
    | 'Big Cowboy Hat'
    | 'Undercut'
    | 'Beanie (blackout)'
    | 'Chill Hat'
    | 'Bucket Hat'
    | 'Fuzzy Banana Bucket Hat'
    | 'Banana Beanie'
    | 'Flame Hat'
    | 'Truck Trucker'
    | 'Rockstar Hair'
    | 'Skull Trucker Hat'
    | 'Helmet'
    | 'Cool Beanie'
    | 'Skinny Headband';

export type TEyeWear =
    | 'Nouns'
    | 'Retro Apple'
    | '24K Gold Blocks'
    | 'Pollocks'
    | 'None'
    | 'Dieter Rams'
    | 'Heatwaves'
    | 'Matisse Frames'
    | 'Mona Lisas'
    | 'Warhols'
    | '6D Glasses'
    | 'Van Goghs'
    | 'Grand Budapest Shades'
    | 'Banksy Goggles'
    | 'Tints (red)'
    | 'Hockney Squares'
    | 'Orange Soda Shades'
    | 'Lensless Glasses'
    | 'Abbey Roads'
    | 'Tints (blue)'
    | 'Tints (yellow)'
    | 'Radiohead Squares'
    | 'Last Supper Squares'
    | 'Rembrandt Goggles'
    | 'Rounded Squares (blackout)'
    | 'Trapezoids'
    | 'Cobain Goggles'
    | 'Golden Hour Frames'
    | 'Mondrian Squares'
    | 'Monet Squares'
    | 'Windsors (blackout)'
    | 'Sunflowers'
    | 'Cali Sunset';

export type T1of1 =
    | 'None'
    | 'Golden y00t'
    | 'Coded y00t'
    | 'Slime y00t'
    | 'Renaissance y00t'
    | 'Colored Pencil y00t'
    | 'Abstract y00t'
    | 'Aqua y00t'
    | 'Balloon y00t'
    | 'Astroy00t'
    | 'Cloud y00t'
    | 'Deconstructed y00t'
    | 'Doodle y00t'
    | 'Elder y00t'
    | 'FACIAL EXPRESSIONS STUDY'
    | "FRANK'S SCRIBBLE"
    | 'Ghosted y00t'
    | 'Giga y00t'
    | 'Ice Cream King y00t'
    | 'Mermaid y00t'
    | 'Mini(dino)'
    | 'Mini(whale)'
    | 'Monochromatic Zombie y00t';
